language: php

php:
  - 5.6

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"

install:
  - composer --prefer-dist --no-interaction install

script:
  - ./bin/php-cs-fixer --dry-run -v fix --config=.php_cs.php
  - ./bin/phpspec run
