pim_icecat_connector:
    settings:
        credentials_username:
            value: akeneo-test
            scope: app
        credentials_password:
            value: akeneo-test44
            scope: app
        locales:
            value: 'EN,FR'
            scope: app
        fallback_locale:
            value: 'US'
            scope: app
        ean_attribute:
            value: icecat_ean
            scope: app
        description:
            value: ~
            scope: app
        short_description:
            value: ~
            scope: app
        summary_description:
            value: ~
            scope: app
        short_summary_description:
            value: ~
            scope: app
        pictures:
            value: ~
            scope: app
