extensions:
    icecat-job-instance-csv-to-csv-import-edit:
        module: pim/form/common/edit-form

    icecat-job-instance-csv-to-csv-import-edit-main-image:
        module: pim/form/common/main-image
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-import-csv.svg

    icecat-job-instance-csv-to-csv-import-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    icecat-job-instance-csv-to-csv-import-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    icecat-job-instance-csv-to-csv-import-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: icecat-job-instance-csv-to-csv-import-edit
        position: 1000

    icecat-job-instance-csv-to-csv-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: content
        position: 100

    icecat-job-instance-csv-to-csv-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: icecat-job-instance-csv-to-csv-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: icecat-job-instance-properties

    icecat-job-instance-csv-to-csv-import-edit-global:
        module: pim/job/common/edit/properties
        parent: icecat-job-instance-csv-to-csv-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode: pim-job-instance-global

    icecat-job-instance-csv-to-csv-import-edit-history:
        module: pim/common/tab/history
        parent: icecat-job-instance-csv-to-csv-import-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: icecat-job-instance-history

    icecat-job-instance-csv-to-csv-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-to-csv-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    icecat-job-instance-csv-to-csv-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-to-csv-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title

    icecat-job-instance-csv-to-csv-import-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-to-csv-import-edit-global
        position: 120
        targetZone: properties
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    icecat-job-instance-csv-to-csv-import-edit-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: icecat-job-instance-csv-to-csv-import-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.upload_allowed.help
            readOnly: false

    icecat-job-instance-csv-to-csv-import-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-to-csv-import-edit-global
        position: 140
        targetZone: properties
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    icecat-job-instance-csv-to-csv-import-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-to-csv-import-edit-global
        position: 150
        targetZone: properties
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    icecat-job-instance-csv-to-csv-import-edit-label:
        module: pim/job/common/edit/label
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: title
        position: 100

    icecat-job-instance-csv-to-csv-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: meta
        position: 100

    icecat-job-instance-csv-to-csv-import-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: buttons
        position: 50

    icecat-job-instance-csv-to-csv-import-edit-delete:
        module: pim/job/import/edit/delete
        parent: icecat-job-instance-csv-to-csv-import-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.import_profile
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    icecat-job-instance-csv-to-csv-import-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: buttons
        position: 120

    icecat-job-instance-csv-to-csv-import-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    icecat-job-instance-csv-to-csv-import-edit-state:
        module: pim/form/common/state
        parent: icecat-job-instance-csv-to-csv-import-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    icecat-job-instance-csv-to-csv-import-edit-validation:
        module: pim/job/common/edit/validation
        parent: icecat-job-instance-csv-to-csv-import-edit
