extensions:
    icecat-enrich-product-import-show:
        module: pim/form/common/edit-form

    icecat-enrich-product-import-show-main-image:
        module: pim/form/common/main-image
        parent: icecat-enrich-product-import-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-import-csv.svg

    icecat-enrich-product-import-show-user-navigation:
        module: pim/menu/user-navigation
        parent: icecat-enrich-product-import-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    icecat-enrich-product-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: icecat-enrich-product-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    icecat-enrich-product-import-show-import-button:
        module: pim/job/common/edit/launch
        parent: icecat-enrich-product-import-show
        targetZone: content
        position: 40
        config:
            label: pim_enrich.form.job_instance.button.import.launch
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    icecat-enrich-product-import-show-subsection:
        module: pim/form/common/subsection
        parent: icecat-enrich-product-import-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    icecat-enrich-product-import-show-grid:
        module: pim/job/common/grid
        parent: icecat-enrich-product-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import

    icecat-enrich-product-import-show-label:
        module: pim/job/common/edit/label
        parent: icecat-enrich-product-import-show
        targetZone: title
        position: 100

    icecat-enrich-product-import-show-edit:
        module: pim/common/redirect
        parent: icecat-enrich-product-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code
