extensions:
    icecat-enrich-product-import-edit:
        module: pim/form/common/edit-form

    icecat-enrich-product-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: icecat-enrich-product-import-edit
        targetZone: content
        position: 100

    icecat-enrich-product-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: icecat-enrich-product-import-edit-tabs
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    icecat-enrich-product-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: icecat-enrich-product-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    icecat-enrich-product-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: icecat-enrich-product-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    icecat-enrich-product-import-show-no-settings:
        module: pimicecatconnector/job/message_no_settings
        parent: icecat-enrich-product-import-show-properties
        position: 110
        targetZone: global-settings

    icecat-enrich-product-import-edit-label:
        module: pim/job/common/edit/label
        parent: icecat-enrich-product-import-edit
        targetZone: title
        position: 100

    icecat-enrich-product-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: icecat-enrich-product-import-edit
        targetZone: meta
        position: 100

    icecat-enrich-product-import-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: icecat-enrich-product-import-edit
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    icecat-enrich-product-import-edit-launch:
        module: pim/job/common/edit/upload-launch
        parent: icecat-enrich-product-import-edit
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: buttons
        position: 110
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code
