extensions:
    icecat-job-instance-xml-base-import-show:
        module: pim/form/common/edit-form

    icecat-job-instance-xml-base-import-show-main-image:
        module: pim/form/common/main-image
        parent: icecat-job-instance-xml-base-import-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-import-csv.svg

    icecat-job-instance-xml-base-import-show-user-navigation:
        module: pim/menu/user-navigation
        parent: icecat-job-instance-xml-base-import-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    icecat-job-instance-xml-base-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: icecat-job-instance-xml-base-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    icecat-job-instance-xml-base-import-show-switcher:
        module: pim/job-instance/import/switcher
        parent: icecat-job-instance-xml-base-import-show
        position: 0
        targetZone: meta

    icecat-job-instance-xml-base-import-show-launch-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: icecat-job-instance-xml-base-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 40
        config:
            label: pim_enrich.form.job_instance.button.import.launch

    icecat-job-instance-xml-base-import-show-file-path:
        module: pim/job/common/file-path
        parent: icecat-job-instance-xml-base-import-show-launch-switcher-item
        config:
            label: pim_enrich.form.job_instance.file_path

    icecat-job-instance-xml-base-import-show-import-button:
        module: pim/job/common/edit/launch
        parent: icecat-job-instance-xml-base-import-show-file-path
        targetZone: buttons
        config:
            label: pim_enrich.form.job_instance.button.import.launch
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    icecat-job-instance-xml-base-import-show-upload-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: icecat-job-instance-xml-base-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 50
        config:
            label: pim_enrich.form.job_instance.button.import.upload_file

    icecat-job-instance-xml-base-import-show-upload:
        module: pim/job/common/edit/upload
        parent: icecat-job-instance-xml-base-import-show-upload-switcher-item
        position: 50
        config:
            type: csv

    icecat-job-instance-xml-base-import-show-upload-button:
        module: pim/job/common/edit/upload-launch
        parent: icecat-job-instance-xml-base-import-show-upload-switcher-item
        position: 60
        config:
            label: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    icecat-job-instance-xml-base-import-show-subsection:
        module: pim/form/common/subsection
        parent: icecat-job-instance-xml-base-import-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    icecat-job-instance-xml-base-import-show-grid:
        module: pim/job/common/grid
        parent: icecat-job-instance-xml-base-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import

    icecat-job-instance-xml-base-import-show-label:
        module: pim/job/common/edit/label
        parent: icecat-job-instance-xml-base-import-show
        targetZone: title
        position: 100

    icecat-job-instance-xml-base-import-show-edit:
        module: pim/common/redirect
        parent: icecat-job-instance-xml-base-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code
