extensions:
    icecat-job-instance-csv-base-import-show:
        module: pim/form/common/edit-form

    icecat-job-instance-csv-base-import-show-tabs:
        module: pim/form/common/form-tabs
        parent: icecat-job-instance-csv-base-import-show
        targetZone: content
        position: 100

    icecat-job-instance-csv-base-import-show-properties:
        module: pim/job/common/edit/properties
        parent: icecat-job-instance-csv-base-import-show-tabs
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: icecat-job-instance-properties

    icecat-job-instance-csv-base-import-show-history:
        module: pim/common/tab/history
        parent: icecat-job-instance-csv-base-import-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: icecat-job-instance-history

    icecat-job-instance-csv-base-import-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    icecat-job-instance-csv-base-import-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    icecat-job-instance-csv-base-import-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    icecat-job-instance-csv-base-import-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    icecat-job-instance-csv-base-import-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    icecat-job-instance-csv-base-import-show-properties-escape:
        module: pim/job/common/edit/field/text
        parent: icecat-job-instance-csv-base-import-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.escape
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.escape.title
            tooltip: pim_enrich.form.job_instance.tab.properties.escape.help

    icecat-job-instance-csv-base-import-show-label:
        module: pim/job/common/edit/label
        parent: icecat-job-instance-csv-base-import-show
        targetZone: title
        position: 100

    icecat-job-instance-csv-base-import-show-meta:
        module: pim/job/common/edit/meta
        parent: icecat-job-instance-csv-base-import-show
        targetZone: meta
        position: 100

    icecat-job-instance-csv-base-import-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: icecat-job-instance-csv-base-import-show
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    icecat-job-instance-csv-base-import-show-edit:
        module: pim/common/redirect
        parent: icecat-job-instance-csv-base-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code

    icecat-job-instance-csv-base-import-show-launch:
        module: pim/job/common/edit/upload-launch
        parent: icecat-job-instance-csv-base-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: buttons
        position: 110
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code
