#!groovy

milestone 1
if (env.BRANCH_NAME =~ /^PR-/) {
    input 'Launch tests?'
}
milestone 2

stage("Tests") {
  withCredentials([string(credentialsId: 'composer-token', variable: 'token')]) {
    podTemplate(label: 'icecat-connector', containers: [
      containerTemplate(
        name: "elasticsearch", 
        image: "elasticsearch:5.5", 
        resourceRequestCpu: '100m', 
        resourceRequestMemory: '200Mi',
        envVars: [
          envVar(key: "ES_JAVA_OPTS", value: "-Xms512m -Xmx512m"),
          envVar(key: "FORCE", value: "true"),
        ]        
      ),
      containerTemplate(
        name: "mysql", 
        image: "mysql:5.7", 
        resourceRequestCpu: '100m', 
        resourceRequestMemory: '200Mi', 
        envVars: [
          envVar(key: "MYSQL_ROOT_PASSWORD", value: "root"),
          envVar(key: "MYSQL_USER", value: "akeneo_pim"),
          envVar(key: "MYSQL_PASSWORD", value: "akeneo_pim"),
          envVar(key: "MYSQL_DATABASE", value: "akeneo_pim"),
        ], volumes: [
          emptyDirVolume(memory: true, mountPath: "/var/lib/mysql"),
          emptyDirVolume(memory: true, mountPath: "/tmp")
        ]
      ),
      containerTemplate(
        name: "php", 
        ttyEnabled: true, 
        command: 'cat', 
        image: "akeneo/php:7.1", 
        resourceRequestCpu: '100m', 
        resourceRequestMemory: '1000Mi',
        envVars: [
          envVar(key: "COMPOSER_AUTH", value: "{\"github-oauth\":{\"github.com\": \"$token\"}}")
        ]
      ),
    ]) {
      node('icecat-connector') {
        container("php") {
          checkout([$class: 'GitSCM',
            branches: [[name: "2.0"]],
            userRemoteConfigs: [[credentialsId: 'github-credentials', url: 'https://github.com/akeneo/pim-enterprise-dev.git']]
          ])

          sh """
            composer config repositories.icecat '{"type": "vcs", "url": "git@github.com:akeneo/icecat-connector.git", "branch": "master"}'
            php -d memory_limit=3G /usr/local/bin/composer require akeneo/icecat-connector:2.0.x-dev --no-interaction --no-progress --prefer-dist
            chmod -R 777 vendor
          """

          dir("vendor/akeneo/icecat-connector") {
            deleteDir()
            checkout scm
          }

          sh """
            composer dump-autoload -o
            rm app/cache/* -rf
            sed -i 's#// your app bundles should be registered here#\\0\\nnew Pim\\\\Bundle\\\\IcecatConnectorBundle\\\\PimIcecatConnectorBundle(),#' app/AppKernel.php
            sed -i 's#// your app bundles should be registered here#\\0\\nnew Pim\\\\Bundle\\\\ExtendedMeasureBundle\\\\PimExtendedMeasureBundle(),#' app/AppKernel.php
            sed -i 's#// your app bundles should be registered here#\\0\\nnew Pim\\\\Bundle\\\\ExtendedAttributeTypeBundle\\\\PimExtendedAttributeTypeBundle(),#' app/AppKernel.php
            cp vendor/akeneo/icecat-connector/src/Resources/jenkins/parameters_test.yml app/config/parameters_test.yml
            cp vendor/akeneo/icecat-connector/src/Resources/jenkins/phpunit.xml app/phpunit.xml
            mkdir -p app/build/logs
            sed -i \"s#index_hosts: .*#index_hosts: '127.0.0.1:9200'#g\" app/config/parameters_test.yml
            sed -i 's/database_host:.*/database_host: 127.0.0.1/' app/config/parameters_test.yml
            sleep 10
          """

          sh "bin/console pim:install --force --env=test"

          try {
            sh "vendor/bin/phpunit -c app/phpunit.xml --log-junit app/build/logs/phpunit.xml"
          } finally {
            junit "app/build/logs/*.xml"
          }
        }
      }
    }
  }
}
