services:
    pim_icecat_connector.job.xml_attribute_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'Icecat features import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@pim_icecat_connector.step.xml_attribute.import'
        tags:
            -
                name: akeneo_batch.job
                connector: 'Icecat'
                type: '%pim_connector.job.import_type%'
