parameters:
    pim_icecat_connector.job.job_parameters.form_configuration_provider.simple_csv.class: Pim\Bundle\IcecatConnectorBundle\JobParameters\FormConfigurationProvider\SimpleCsvConfiguration

services:
    #--------------------------------------------------------------------------
    # prepare features CSV mapping file job
    #--------------------------------------------------------------------------
    pim_icecat_connector.job.xml_features_download:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'icecat_download_features'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_icecat_connector.step.download_features.mapping'
        tags:
            -
                name: akeneo_batch.job
                connector: 'Icecat'
                type: '%pim_connector.job.import_type%'

    #--------------------------------------------------------------------------
    # import features mapping job
    #--------------------------------------------------------------------------
    pim_icecat_connector.job.import_features_mapping:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'icecat_import_features_mapping'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@pim_icecat_connector.step.import_features.mapping'
        tags:
            -
                name: akeneo_batch.job
                connector: 'Icecat'
                type: '%pim_connector.job.import_type%'

    #--------------------------------------------------------------------------
    # Enrich products with Icecat
    #--------------------------------------------------------------------------
    pim_icecat_connector.job.enrich_products_init:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'icecat_enrich_products'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_icecat_connector.step.enrich_products_init'
        tags:
            -
                name: akeneo_batch.job
                connector: 'Icecat'
                type: '%pim_connector.job.import_type%'

    #--------------------------------------------------------------------------
    # Default providers
    #--------------------------------------------------------------------------
    pim_icecat_connector.job.job_parameters.default_values_provider.enrich_products:
        class: Pim\Bundle\IcecatConnectorBundle\JobParameters\DefaultValuesProvider\EnrichProducts
        arguments:
            -
                - 'icecat_enrich_products'
            - []
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_icecat_connector.job.job_parameters.default_values_provider.download_xml_to_csv:
        class: Pim\Bundle\IcecatConnectorBundle\JobParameters\DefaultValuesProvider\XmlToCsvDownload
        arguments:
            -
                - 'icecat_download_features'
            -
                filename: 'FeaturesList.xml.gz'
                filePath: '/tmp/featuresList.csv'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_icecat_connector.job.job_parameters.default_values_provider.csv_to_csv:
        class: Pim\Bundle\IcecatConnectorBundle\JobParameters\DefaultValuesProvider\CsvToCsvImport
        arguments:
            -
                - 'icecat_import_features_mapping'
            -
                outputFilePath: '/tmp/mapping.csv'
                uploadAllowed: true
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_icecat_connector.job.job_parameters.constraint_collection_provider.empty:
        class: '%akeneo_batch.job.job_parameters.empty_constraint_collection_provider.class%'
        arguments:
            -
                - 'icecat_download_features'
                - 'icecat_import_features_mapping'
                - 'icecat_enrich_products'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pim_icecat_connector.job.job_parameters.form_configuration_provider.empty:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                icecat_enrich_products: pim-job-instance-csv-base-import
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }

    pim_icecat_connector.job.job_parameters.form_configuration_provider.simple_csv_download:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                icecat_download_features: icecat-job-instance-csv-base-import
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }

    pim_icecat_connector.job.job_parameters.form_configuration_provider.csv_to_csv:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                icecat_import_features_mapping: icecat-job-instance-csv-to-csv-import
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
