config:
    paths:
        pimicecatconnector/system/configuration: pimicecatconnector/js/form/system
        pimicecatconnector/template/system/group/configuration: pimicecatconnector/js/templates/system/group/configuration.html
        pimicecatconnector/job/message_no_settings: pimicecatconnector/js/job/message_no_settings
        pimicecatconnector/template/job/no_settings: pimicecatconnector/js/templates/job/no_settings.html
