services:
#    pim_icecat_connector.step.xml_features.mapping:
#        class: '%pim_connector.step.item_step.class%'
#        arguments:
#            - 'import'
#            - '@event_dispatcher'
#            - '@akeneo_batch.job_repository'
#            - '@pim_icecat_connector.reader.file.xml_features'
#            - '@pim_icecat_connector.mapping.processor.normalization.feature'
#            - '@pim_connector.writer.file.csv'
